export const toadd = 
[
    {
      "category": 1,
      "count": 10,
      "description_En": "Wireless gaming controller for PC and consoles",
      "description_Ua": "Бездротовий ігровий контролер для ПК та консолей",
      "name_En": "Wireless Gaming Controller",
      "name_Ua": "Бездротовий ігровий контролер",
      "price_En": "50",
      "price_Ua": "1200",
      "sale": 0
    },
    {
      "category": 2,
      "count": 5,
      "description_En": "Stainless steel microwave oven with advanced cooking options",
      "description_Ua": "Мікрохвильова піч з нержавіючої сталі з розширеними опціями приготування",
      "name_En": "Stainless Steel Microwave Oven",
      "name_Ua": "Мікрохвильова піч з нержавіючої сталі",
      "price_En": "150",
      "price_Ua": "4000",
      "sale": 0
    },
    {
      "category": 3,
      "count": 8,
      "description_En": "High-performance desktop computer with latest Intel processor",
      "description_Ua": "Настільний комп'ютер високої продуктивності з останнім процесором Intel",
      "name_En": "High-Performance Desktop PC",
      "name_Ua": "Настільний комп'ютер високої продуктивності",
      "price_En": "1200",
      "price_Ua": "32000",
      "sale": 0
    },
    {
      "category": 4,
      "count": 15,
      "description_En": "5G smartphone with AI-powered camera and long battery life",
      "description_Ua": "Смартфон 5G з камерою на штучному інтелекті та довгою автономністю",
      "name_En": "5G Smartphone",
      "name_Ua": "Смартфон 5G",
      "price_En": "800",
      "price_Ua": "22000",
      "sale": 0
    },
    {
      "category": 5,
      "count": 6,
      "description_En": "10-inch tablet with high-resolution display and quad-core processor",
      "description_Ua": "Планшет з 10-дюймовим дисплеєм високої роздільної здатності та чотирьохядерним процесором",
      "name_En": "10-inch High-Resolution Tablet",
      "name_Ua": "Планшет з 10-дюймовим дисплеєм",
      "price_En": "300",
      "price_Ua": "8000",
      "sale": 0
    },
    {
      "category": 6,
      "count": 3,
      "description_En": "High-speed HDMI cables for 4K video and audio transmission",
      "description_Ua": "Високошвидкісні HDMI кабелі для передачі відео та аудіо в форматі 4K",
      "name_En": "High-Speed HDMI Cables",
      "name_Ua": "HDMI кабелі високої швидкості",
      "price_En": "20",
      "price_Ua": "500",
      "sale": 0
    },
    {
      "category": 7,
      "count": 13,
      "description_En": "Bluetooth speakers with waterproof design for outdoor use",
      "description_Ua": "Bluetooth-колонки з водонепроникним дизайном для використання на вулиці",
      "name_En": "Waterproof Bluetooth Speakers",
      "name_Ua": "Bluetooth-колонки водонепроникні",
      "price_En": "70",
      "price_Ua": "1800",
      "sale": 0
    },
    {
      "category": 1,
      "count": 12,
      "description_En": "Dual-shock wireless gamepad with ergonomic design",
      "description_Ua": "Бездротовий геймпад з двома вібромоторами та ергономічним дизайном",
      "name_En": "Dual-Shock Wireless Gamepad",
      "name_Ua": "Бездротовий геймпад з двома вібромоторами",
      "price_En": "40",
      "price_Ua": "1000",
      "sale": 0
    },
    {
      "category": 2,
      "count": 7,
      "description_En": "Compact microwave oven with easy-to-use control panel",
      "description_Ua": "Компактна мікрохвильова піч з простим в управління панеллю",
      "name_En": "Compact Microwave Oven",
      "name_Ua": "Компактна мікрохвильова піч",
      "price_En": "120",
      "price_Ua": "3200",
      "sale": 0
    },
    {
      "category": 3,
      "count": 9,
      "description_En": "Ultra-slim desktop computer with touchscreen monitor",
      "description_Ua": "Ультратонкий настільний комп'ютер з сенсорним монітором",
      "name_En": "Ultra-Slim Desktop PC",
      "name_Ua": "Ультратонкий настільний комп'ютер",
      "price_En": "1500",
      "price_Ua": "38000",
      "sale": 0
    },
    {
      "category": 4,
      "count": 18,
      "description_En": "Smartphone with triple-camera setup and AI enhancements",
      "description_Ua": "Смартфон з потрійною камерою та підвищенням на штучному інтелекті",
      "name_En": "Triple-Camera Smartphone",
      "name_Ua": "Смартфон з потрійною камерою",
      "price_En": "1000",
      "price_Ua": "26000",
      "sale": 0
    },
    {
      "category": 5,
      "count": 4,
      "description_En": "Large-screen tablet with pen support and 4G connectivity",
      "description_Ua": "Планшет з великим екраном, підтримкою пенсила та підключенням 4G",
      "name_En": "Large-Screen Tablet",
      "name_Ua": "Планшет з великим екраном",
      "price_En": "400",
      "price_Ua": "10000",
      "sale": 0
    },
    {
      "category": 6,
      "count": 2,
      "description_En": "Ethernet cables for reliable network connections",
      "description_Ua": "Етернет-кабелі для надійних мережевих з'єднань",
      "name_En": "Ethernet Cables",
      "name_Ua": "Етернет-кабелі",
      "price_En": "15",
      "price_Ua": "400",
      "sale": 0
    },
    {
      "category": 7,
      "count": 10,
      "description_En": "Portable Bluetooth speakers with extended battery life",
      "description_Ua": "Портативні Bluetooth-колонки з підвищеною часом автономної роботи",
      "name_En": "Portable Bluetooth Speakers",
      "name_Ua": "Портативні Bluetooth-колонки",
      "price_En": "60",
      "price_Ua": "1500",
      "sale": 0
    },
    {
      "category": 1,
      "count": 11,
      "description_En": "Racing-style gamepad with customizable buttons",
      "description_Ua": "Геймпад у стилі гонок з налаштовуваними кнопками",
      "name_En": "Racing-Style Gamepad",
      "name_Ua": "Геймпад у стилі гонок",
      "price_En": "45",
      "price_Ua": "1100",
      "sale": 0
    },
    {
      "category": 2,
      "count": 6,
      "description_En": "Digital microwave oven with smart cooking presets",
      "description_Ua": "Цифрова мікрохвильова піч з інтелектуальними режимами приготування",
      "name_En": "Digital Microwave Oven",
      "name_Ua": "Цифрова мікрохвильова піч",
      "price_En": "180",
      "price_Ua": "4800",
      "sale": 0
    },
    {
      "category": 3,
      "count": 7,
      "description_En": "Gaming desktop computer with RGB lighting and liquid cooling",
      "description_Ua": "Ігровий настільний комп'ютер з підсвіткою RGB та рідинним охолодженням",
      "name_En": "Gaming Desktop PC",
      "name_Ua": "Ігровий настільний комп'ютер",
      "price_En": "2000",
      "price_Ua": "52000",
      "sale": 0
    },
    {
      "category": 4,
      "count": 20,
      "description_En": "Foldable smartphone with dual-screen display and 5G connectivity",
      "description_Ua": "Складний смартфон з двома екранами і підтримкою мережі 5G",
      "name_En": "Foldable Smartphone",
      "name_Ua": "Складний смартфон",
      "price_En": "1500",
      "price_Ua": "38000",
      "sale": 0
    },
    {
      "category": 5,
      "count": 3,
      "description_En": "Tablet with detachable keyboard and Full HD display",
      "description_Ua": "Планшет з від'ємною клавіатурою та дисплеєм Full HD",
      "name_En": "Tablet with Detachable Keyboard",
      "name_Ua": "Планшет з від'ємною клавіатурою",
      "price_En": "500",
      "price_Ua": "13000",
      "sale": 0
    },
    {
      "category": 6,
      "count": 1,
      "description_En": "Fiber optic cables for high-speed data transmission",
      "description_Ua": "Оптичні кабелі для передачі даних високої швидкості",
      "name_En": "Fiber Optic Cables",
      "name_Ua": "Оптичні кабелі",
      "price_En": "30",
      "price_Ua": "800",
      "sale": 0
    },
    {
      "category": 7,
      "count": 8,
      "description_En": "Wireless speakers with built-in voice assistant and weather resistance",
      "description_Ua": "Бездротові колонки з вбудованим голосовим асистентом та захистом від погодних умов",
      "name_En": "Weather-Resistant Wireless Speakers",
      "name_Ua": "Бездротові колонки з захистом від погодних умов",
      "price_En": "80",
      "price_Ua": "2000",
      "sale": 0
    },
    {
      "category": 1,
      "count": 9,
      "description_En": "Arcade-style gamepad with turbo function and LED indicators",
      "description_Ua": "Геймпад у стилі аркади з функцією турбо та світлодіодними індикаторами",
      "name_En": "Arcade-Style Gamepad",
      "name_Ua": "Геймпад у стилі аркади",
      "price_En": "55",
      "price_Ua": "1400",
      "sale": 0
    },
    {
      "category": 2,
      "count": 4,
      "description_En": "Convection microwave oven with sensor cooking technology",
      "description_Ua": "Конвекційна мікрохвильова піч з технологією сенсорного приготування",
      "name_En": "Convection Microwave Oven",
      "name_Ua": "Конвекційна мікрохвильова піч",
      "price_En": "250",
      "price_Ua": "6400",
      "sale": 0
    },
    {
      "category": 3,
      "count": 5,
      "description_En": "All-in-one desktop computer with touchscreen and 4K display",
      "description_Ua": "Все-в-одному настільному комп'ютері з сенсорним екраном та дисплеєм 4K",
      "name_En": "All-in-One Desktop PC",
      "name_Ua": "Все-в-одному настільному комп'ютері",
      "price_En": "1800",
      "price_Ua": "46000",
      "sale": 0
    },
    {
      "category": 4,
      "count": 25,
      "description_En": "Smartphone with foldable design and enhanced gaming capabilities",
      "description_Ua": "Смартфон з складним дизайном та покращеними ігровими можливостями",
      "name_En": "Foldable Gaming Smartphone",
      "name_Ua": "Смартфон з ігровими можливостями",
      "price_En": "1200",
      "price_Ua": "32000",
      "sale": 0
    },
    {
      "category": 5,
      "count": 2,
      "description_En": "Large-sized tablet with pen support and OLED display",
      "description_Ua": "Планшет великого розміру з підтримкою пенсила та OLED-дисплеєм",
      "name_En": "Large-Sized Tablet",
      "name_Ua": "Планшет великого розміру",
      "price_En": "700",
      "price_Ua": "18000",
      "sale": 0
    },
    {
      "category": 6,
      "count": 3,
      "description_En": "High-quality HDMI cables with gold-plated connectors",
      "description_Ua": "Високоякісні HDMI кабелі з золотими покриттям контактів",
      "name_En": "High-Quality HDMI Cables",
      "name_Ua": "HDMI кабелі високої якості",
      "price_En": "25",
      "price_Ua": "600",
      "sale": 0
    },
    {
      "category": 7,
      "count": 12,
      "description_En": "Portable speakers with built-in microphone for hands-free calls",
      "description_Ua": "Портативні колонки з вбудованим мікрофоном для бездотичних дзвінків",
      "name_En": "Portable Speakers with Microphone",
      "name_Ua": "Портативні колонки з мікрофоном",
      "price_En": "50",
      "price_Ua": "1300",
      "sale": 0
    },
    {
      "category": 1,
      "count": 8,
      "description_En": "Wireless gamepad with programmable buttons and vibration feedback",
      "description_Ua": "Бездротовий геймпад з програмованими кнопками та вібраційною відгукою",
      "name_En": "Programmable Wireless Gamepad",
      "name_Ua": "Бездротовий геймпад з програмованими кнопками",
      "price_En": "60",
      "price_Ua": "1500",
      "sale": 0
    },
    {
      "category": 2,
      "count": 3,
      "description_En": "Built-in microwave oven with grill function and child lock",
      "description_Ua": "Вбудована мікрохвильова піч з функцією гриля та захистом для дітей",
      "name_En": "Built-In Microwave Oven",
      "name_Ua": "Вбудована мікрохвильова піч",
      "price_En": "350",
      "price_Ua": "9000",
      "sale": 0
    },
    {
      "category": 3,
      "count": 4,
      "description_En": "Mini gaming desktop computer with compact design and powerful GPU",
      "description_Ua": "Міні ігровий настільний комп'ютер з компактним дизайном та потужною відеокартою",
      "name_En": "Mini Gaming Desktop PC",
      "name_Ua": "Міні ігровий настільний комп'ютер",
      "price_En": "1600",
      "price_Ua": "42000",
      "sale": 0
    },
    {
      "category": 4,
      "count": 30,
      "description_En": "Smartphone with AI-powered camera and ultra-fast charging",
      "description_Ua": "Смартфон з камерою на штучному інтелекті та ультрашвидким заряджанням",
      "name_En": "AI-Powered Camera Smartphone",
      "name_Ua": "Смартфон з камерою на штучному інтелекті",
      "price_En": "1300",
      "price_Ua": "34000",
      "sale": 0
    },
    {
      "category": 5,
      "count": 1,
      "description_En": "Convertible tablet with pen and keyboard included",
      "description_Ua": "Трансформерний планшет з пенсилом та клавіатурою в комплекті",
      "name_En": "Convertible Tablet with Pen",
      "name_Ua": "Трансформерний планшет з пенсилом",
      "price_En": "600",
      "price_Ua": "16000",
      "sale": 0
    },
    {
      "category": 6,
      "count": 2,
      "description_En": "Long Ethernet cables for home and office networking",
      "description_Ua": "Довгі етернет-кабелі для домашнього та офісного мережування",
      "name_En": "Long Ethernet Cables",
      "name_Ua": "Довгі етернет-кабелі",
      "price_En": "35",
      "price_Ua": "900",
      "sale": 0
    },
    {
      "category": 7,
      "count": 9,
      "description_En": "Portable waterproof speakers with Bluetooth connectivity",
      "description_Ua": "Портативні водонепроникні колонки з підтримкою Bluetooth",
      "name_En": "Waterproof Portable Speakers",
      "name_Ua": "Портативні водонепроникні колонки",
      "price_En": "75",
      "price_Ua": "1900",
      "sale": 0
    },
    {
      "category": 1,
      "count": 7,
      "description_En": "Wireless gamepad with built-in rechargeable battery and turbo mode",
      "description_Ua": "Бездротовий геймпад з вбудованою акумуляторною батареєю та турбо режимом",
      "name_En": "Rechargeable Wireless Gamepad",
      "name_Ua": "Бездротовий геймпад з акумулятором",
      "price_En": "70",
      "price_Ua": "1800",
      "sale": 0
    },
    {
      "category": 2,
      "count": 2,
      "description_En": "Over-the-range microwave oven with exhaust fan and sensor cooking",
      "description_Ua": "Мікрохвильова піч над кухонною плитою з витяжною вентиляцією та сенсорним приготуванням",
      "name_En": "Over-the-Range Microwave Oven",
      "name_Ua": "Мікрохвильова піч над плитою",
      "price_En": "400",
      "price_Ua": "11000",
      "sale": 0
    },
    {
      "category": 3,
      "count": 3,
      "description_En": "Powerful gaming desktop computer with liquid cooling system",
      "description_Ua": "Потужний ігровий настільний комп'ютер з системою рідинного охолодження",
      "name_En": "Powerful Gaming Desktop PC",
      "name_Ua": "Потужний ігровий настільний комп'ютер",
      "price_En": "2500",
      "price_Ua": "64000",
      "sale": 0
    },
    {
      "category": 4,
      "count": 35,
      "description_En": "Flagship smartphone with premium design and top-tier camera",
      "description_Ua": "Флагманський смартфон з преміальним дизайном та кращою камерою",
      "name_En": "Flagship Smartphone",
      "name_Ua": "Флагманський смартфон",
      "price_En": "1800",
      "price_Ua": "46000",
      "sale": 0
    },
    {
      "category": 5,
      "count": 5,
      "description_En": "Slim and lightweight tablet with AMOLED display and 5G connectivity",
      "description_Ua": "Тонкий та легкий планшет з AMOLED дисплеєм та підтримкою мережі 5G",
      "name_En": "Slim AMOLED Tablet",
      "name_Ua": "Тонкий планшет з AMOLED дисплеєм",
      "price_En": "800",
      "price_Ua": "20000",
      "sale": 0
    },
    {
      "category": 6,
      "count": 4,
      "description_En": "Flat Ethernet cables for neat and efficient networking solutions",
      "description_Ua": "Плоскі етернет-кабелі для аккуратних та ефективних мережних рішень",
      "name_En": "Flat Ethernet Cables",
      "name_Ua": "Плоскі етернет-кабелі",
      "price_En": "20",
      "price_Ua": "500",
      "sale": 0
    },
    {
      "category": 7,
      "count": 6,
      "description_En": "Wireless party speakers with LED lights and microphone input",
      "description_Ua": "Бездротові вечірні колонки з світлодіодними лампочками та мікрофонним входом",
      "name_En": "Wireless Party Speakers",
      "name_Ua": "Бездротові вечірні колонки",
      "price_En": "100",
      "price_Ua": "2500",
      "sale": 0
    },
    {
      "category": 1,
      "count": 5,
      "description_En": "Dual charging dock for wireless gamepads with LED charge indicators",
      "description_Ua": "Двоканальна док-станція для бездротових геймпадів з індикаторами заряду LED",
      "name_En": "Dual Charging Dock for Gamepads",
      "name_Ua": "Двоканальна док-станція для геймпадів",
      "price_En": "35",
      "price_Ua": "900",
      "sale": 0
    },
    {
      "category": 2,
      "count": 7,
      "description_En": "Stainless steel microwave oven with multiple power levels",
      "description_Ua": "Нержавіюча стальна мікрохвильова піч з кількома рівнями потужності",
      "name_En": "Stainless Steel Microwave Oven",
      "name_Ua": "Нержавіюча стальна мікрохвильова піч",
      "price_En": "300",
      "price_Ua": "8000",
      "sale": 0
    },
    {
      "category": 3,
      "count": 2,
      "description_En": "Compact gaming desktop computer with RGB lighting and fast CPU",
      "description_Ua": "Компактний ігровий настільний комп'ютер з підсвіткою RGB та швидким процесором",
      "name_En": "Compact Gaming Desktop PC",
      "name_Ua": "Компактний ігровий настільний комп'ютер",
      "price_En": "1300",
      "price_Ua": "34000",
      "sale": 0
    },
    {
      "category": 4,
      "count": 40,
      "description_En": "Mid-range smartphone with versatile camera and long battery life",
      "description_Ua": "Смартфон середнього класу з універсальною камерою та довгим терміном служби акумулятора",
      "name_En": "Mid-Range Smartphone",
      "name_Ua": "Смартфон середнього класу",
      "price_En": "800",
      "price_Ua": "20000",
      "sale": 0
    },
    {
      "category": 5,
      "count": 6,
      "description_En": "Tablet with robust construction and anti-glare screen",
      "description_Ua": "Планшет з міцною конструкцією та антиблисковим екраном",
      "name_En": "Rugged Tablet",
      "name_Ua": "Міцний планшет",
      "price_En": "550",
      "price_Ua": "14000",
      "sale": 0
    },
    {
      "category": 6,
      "count": 5,
      "description_En": "High-speed Ethernet cables for optimal internet performance",
      "description_Ua": "Етернет-кабелі високої швидкості для оптимальної інтернет-працездатності",
      "name_En": "High-Speed Ethernet Cables",
      "name_Ua": "Етернет-кабелі високої швидкості",
      "price_En": "30",
      "price_Ua": "700",
      "sale": 0
    },
    {
      "category": 7,
      "count": 3,
      "description_En": "Portable speakers with RGB lighting and microphone input",
      "description_Ua": "Портативні колонки з підсвіткою RGB та мікрофонним входом",
      "name_En": "RGB Portable Speakers",
      "name_Ua": "Портативні колонки з підсвіткою RGB",
      "price_En": "65",
      "price_Ua": "1700",
      "sale": 0
    }
  ]
  